name: jumia_clone
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
#--------------------------dependencies--------------------------#
dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.1.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  package_info_plus: ^8.0.2
  flutter_localizations:
    sdk: flutter

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # state management
  get: ^4.6.5
  get_storage: ^2.1.1

  # product platform_specific:
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  android_12:
    image: assets/logos/luna-store-splash-logo-white.png
    image_dark: assets/logos/luna-store-splash-logo-black.png
  android: true
  ios: true
  web: false
  #  color: "#FFFFFF"
  #  color_dark: "#272727"
  #  image: assets/logos/luna-store-splash-logo-black-removebg-preview.png
  #  image_dark: assets/logos/luna-store-splash-logo-white-removebg-preview.png
  #-------------------------- ./ packages end --------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #-------------------------- local assets --------------------------#
  assets:
    - assets/logos/
    - assets/images/onboarding_images/
    - assets/images/animations/
    - assets/logos/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/nike-shoes.png
    - assets/images/products/nike-shoes.png
    - assets/images/products/product-jacket.png
    - assets/images/products/product-jeans.png
    - assets/images/products/product-shirt.png
    - assets/images/products/product-slippers.png
    - assets/images/products/nike-air-redandblack.png
    - assets/images/products/nike-air-orange.jpg
    - assets/images/products/nike-air-white-magenta.webp
    - assets/images/products/nike-air-white and red.jpg
    - assets/images/products/ssmsung-s23-mobile.jpg
    - assets/images/products/samsung-s23-mobile-white-back.png
    - assets/images/products/samsung-s23-back.webp
    - assets/images/products/Apple_iPhone-13-Pro_iPhone-13-Pro-Max.jpg
    - assets/images/products/Iphone-13-pro-max-back.jpg
    - assets/images/products/iphone-13-pro-max-dual-side.jpg
    - assets/images/products/apple-iphone-13-pro-max-front.png
    - assets/images/products/toni-dogfood.png
    - assets/images/products/nike air jordar 4 single blue.jpg
    - assets/images/products/nike air jordar 4 single orange.jpg
    - assets/images/products/nike air max.webp
    - assets/images/products/nike backetball shoe green black.webp
    - assets/images/products/nike wild horse.jpg
    - assets/images/products/track-suit-black.jpg
    - assets/images/products/track-suit-blue.jpg
    - assets/images/products/track suit red.jpg
    - assets/images/products/track-suit-parrot-green.jpg
    - assets/images/products/adidas-football.jpg
    - assets/images/products/baseball-bat.jpg
    - assets/images/products/criket-bat.jpg
    - assets/images/products/tennis-racket.webp
    - assets/images/products/bedroom-bed.jpg
    - assets/images/products/bedroom-lamp.jpg
    - assets/images/user/user-image.png
    - assets/icons/brands/nike-icon.png
    - assets/icons/payment-methods/paypal-icon.png
    - assets/icons/payment-methods/apple-pay.png
    - assets/icons/payment-methods/google-pay.png
    - assets/icons/payment-methods/credit-card.png
    - assets/icons/payment-methods/master-card.png
    - assets/icons/payment-methods/visa.png
    - assets/icons/payment-methods/paystock.png
    - assets/icons/payment-methods/paytm.png
    - assets/icons/payment-methods/payment-seccussfully.gif

  #-------------------------- local fonts --------------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

