name: jumia_clone
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


#--------------------------dependencies--------------------------#
dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.1.0
  intl: ^0.19.0
  intl_utils: ^2.8.7
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  package_info_plus: ^8.0.2
  flutter_localizations:
    sdk: flutter

  # icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # state management
  get: ^4.6.5
  get_storage: ^2.1.1

  # product platform_specific:
  carousel_slider: ^4.2.1
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  lottie: ^3.1.2
  connectivity_plus: ^6.0.5

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#272727"
  android_12:
    image: assets/logos/luna-store-splash-logo-white.png
    image_dark: assets/logos/luna-store-splash-logo-black.png
  android: true
  ios: true
  web: false

  #-------------------------- ./ packages end --------------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

#--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800