// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEs4PfgHdzA9ljT3sPN_E5KgrqMOq8Ms4',
    appId: '1:159041878467:android:2ecf4d1f868c6b0fc86576',
    messagingSenderId: '159041878467',
    projectId: 'hta-eb132',
    storageBucket: 'hta-eb132.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjqG96atU4gORI9Rd9tvXJN9e5LYYn3kg',
    appId: '1:159041878467:ios:284045669567b074c86576',
    messagingSenderId: '159041878467',
    projectId: 'hta-eb132',
    storageBucket: 'hta-eb132.appspot.com',
    androidClientId: '159041878467-d8ta9bnno64st9j6prb11nep6gecd4lk.apps.googleusercontent.com',
    iosClientId: '159041878467-en498da8of78da5jf961k95ejab77ees.apps.googleusercontent.com',
    iosBundleId: 'com.example.jumiaClone',
  );

}